version: '3'

services:
  servernode:
    container_name: servernode-practica2
    restart: always
    build: ./Backend_node
    image: josadriang/servernode-practica2
    ports:
      - "5000:5000"
  
  frontend:
    container_name: frontend-practica2
    restart: always
    build: ./Frontend
    image: josadriang/front-practica2
    ports:
      - "3000:3000"
    depends_on:
      - servernode
    links:
      - servernode