version: '3'

services:
  db:
    container_name: db-prac1
    restart: always
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'operaciones'
      MYSQL_ROOT_PASSWORD: '0000'
      TZ: 'US/Central'
    volumes:
      - data:/var/lib/mysql

  servidor:
    container_name: backend
    restart: always
    build: ./servidor
    image: josadriang/back-prac1
    ports:
      - "8080:8080"
    volumes:
      - "/bash:/backend"
    depends_on:
      - db
    links:
      - "db:database" 

  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    image: josadriang/front-prac1
    ports:
      - "3000:3000"
    depends_on:
      - servidor
    links:
      - servidor

  bash:
    container_name: script-bash
    build: ./bash
    image: josadriang/script-prac1
    command: sleep infinity
    volumes:
      - "/bash:/backend"
    

volumes:
  data:
